spring:
  datasource:
    druid:
      url: jdbc:mysql://106.14.183.86:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    host: 106.14.183.86
    port: 6379
    password: 123456
#    sentinel:
#      master: mymaster
#      nodes: 106.14.183.86:26379,106.14.183.86:26380,106.14.183.86:26381

mybatis:
  type-aliases-package: com.shu.cashbook.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8000

#debug: true
